# Generated by Django 2.2.7 on 2019-11-21 13:16

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('short_text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Короткий текст')),
                ('full_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Полный текст')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать')),
                ('is_on_home', models.BooleanField(default=True, verbose_name='Отображать на главной странице')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
