# Generated by Django 2.2.7 on 2019-12-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Образовательная организация'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Контактный телефон'),
        ),
    ]
