# Generated by Django 2.2.7 on 2019-12-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Страна/регион/город'),
        ),
    ]
